<a href="https://colab.research.google.com/github/mirzaaa101/Pairwise-Distance-Calculation-Python/blob/main/distance_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import os
import glob
import pandas as pd
import numpy as np
from sklearn.metrics import pairwise_distances_chunked
import matplotlib.pyplot as plt

PATH = "/content/drive/MyDrive/Upwork/"
df = pd.read_excel(f"{PATH}sample_data.xlsx")
df.head()

roofzipcode  rooflatitude  rooflongitude   code
0  75217-3525      32.72692      -96.64140  73443
1  75217-3157      32.74839      -96.64530  59321
2  75214-4004      32.81262      -96.73865  24757
3  75043-8909      32.86000      -96.61690  65139
4  75159-5104      32.59336      -96.55544  68892

In [7]:
df_small = df.head(3)
df_small.head()

roofzipcode  rooflatitude  rooflongitude   code
0  75217-3525      32.72692      -96.64140  73443
1  75217-3157      32.74839      -96.64530  59321
2  75214-4004      32.81262      -96.73865  24757

In [8]:
df_small.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   roofzipcode    3 non-null      object 
 1   rooflatitude   3 non-null      float64
 2   rooflongitude  3 non-null      float64
 3   code           3 non-null      int64  
dtypes: float64(2), int64(1), object(1)
memory usage: 224.0+ bytes


In [9]:
df_small['rooflongitude'] = df_small['rooflongitude'].astype(str)
df_small['rooflongitude'] = df_small['rooflongitude'].str.replace('-', '')
df_small['rooflongitude'] = df_small['rooflongitude'].astype(float)

<ipython-input-9-8f20481ac0a4>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_small['rooflongitude'] = df_small['rooflongitude'].astype(str)
<ipython-input-9-8f20481ac0a4>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_small['rooflongitude'] = df_small['rooflongitude'].str.replace('-', '')
<ipython-input-9-8f20481ac0a4>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the docum

In [10]:
X = np.array(df_small[["rooflatitude", "rooflongitude"]].values)
X.shape

(3, 2)

In [11]:
X

array([[32.72692, 96.6414 ],
       [32.74839, 96.6453 ],
       [32.81262, 96.73865]])

In [ ]:
# OBSERVED DISTANCE BY NHCCPHC
1-2:2
1-3:13
2-3:11

In [12]:
def vicenty_distance(point1, point2):
    lat1, lon1 = np.radians(point1)
    lat2, lon2 = np.radians(point2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = np.sin(dlat / 2) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2) ** 2
    c = 2 * np.arcsin(np.sqrt(a))

    radius = 6371000  # Earth Radius in meters
    distance = radius * c
    return distance

In [13]:
D = pairwise_distances_chunked(X, metric="haversine")
for chunk in D:
    print(chunk)

[[0.         0.02149147 0.08812234]
 [0.02149147 0.         0.0669467 ]
 [0.08812234 0.0669467  0.        ]]


In [15]:
D = pairwise_distances_chunked(X, metric=vicenty_distance)
for chunk in D:
    print(chunk/1000)

[[ 0.          2.41506223 13.17145639]
 [ 2.41506223  0.         11.27696606]
 [13.17145639 11.27696606  0.        ]]


In [16]:
D = pairwise_distances_chunked(X, metric=vicenty_distance)
for chunk in D:
    print(chunk//1000)

[[ 0.  2. 13.]
 [ 2.  0. 11.]
 [13. 11.  0.]]
