<a href="https://colab.research.google.com/github/mirzaaa101/Pairwise-Distance-Calculation-Python/blob/main/distance_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os
import glob
import pandas as pd
import numpy as np
from sklearn.metrics import pairwise_distances_chunked
import matplotlib.pyplot as plt

PATH = "/content/drive/MyDrive/Upwork/"
df = pd.read_excel(f"{PATH}sample_data.xlsx")
df.head()

roofzipcode  rooflatitude  rooflongitude   code
0  75217-3525      32.72692      -96.64140  73443
1  75217-3157      32.74839      -96.64530  59321
2  75214-4004      32.81262      -96.73865  24757
3  75043-8909      32.86000      -96.61690  65139
4  75159-5104      32.59336      -96.55544  68892

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93137 entries, 0 to 93136
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   roofzipcode    93137 non-null  object 
 1   rooflatitude   93137 non-null  float64
 2   rooflongitude  93137 non-null  float64
 3   code           93137 non-null  int64  
dtypes: float64(2), int64(1), object(1)
memory usage: 2.8+ MB


In [ ]:
df['rooflongitude'] = df['rooflongitude'].astype(str)
df['rooflongitude'] = df['rooflongitude'].str.replace('-', '')
df['rooflongitude'] = df['rooflongitude'].astype(float)

In [ ]:
X = np.array(df[["rooflatitude", "rooflongitude"]].values)
X.shape

(93137, 2)

In [ ]:
def vicenty_distance(point1, point2):
    lat1, lon1 = np.radians(point1)
    lat2, lon2 = np.radians(point2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = np.sin(dlat / 2) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2) ** 2
    c = 2 * np.arcsin(np.sqrt(a))

    radius = 6371000  # Earth Radius in meters
    distance = radius * c
    return distance

In [ ]:
D = pairwise_distances_chunked(X, metric="haversine")

In [ ]:
for chunk in D:
    print(chunk)

[[0.         0.02149147 0.08812234 ... 0.13166273 0.12848112 0.23933522]
 [0.02149147 0.         0.0669467  ... 0.11040407 0.10703179 0.21784585]
 [0.08812234 0.0669467  0.         ... 0.0435685  0.04153002 0.15303347]
 ...
 [0.01435611 0.00926595 0.0757378  ... 0.11906191 0.1153643  0.22577531]
 [0.0550002  0.05523249 0.08716652 ... 0.12563597 0.12697042 0.23609945]
 [0.12455867 0.10306846 0.04005748 ... 0.0197905  0.00932544 0.11477812]]
[[0.24517343 0.22369173 0.159201   ... 0.11721234 0.11767593 0.00691685]
 [0.20098347 0.17952551 0.11358636 ... 0.07058251 0.07250572 0.04096553]
 [0.07761977 0.09619432 0.15448004 ... 0.19648323 0.19595223 0.30717977]
 ...
 [0.20906286 0.18759059 0.12184166 ... 0.07896678 0.08063013 0.03251043]
 [0.09669549 0.07883971 0.0354972  ... 0.05595659 0.06060574 0.16387187]
 [0.16677976 0.18431142 0.23659337 ... 0.27577888 0.27705478 0.38596335]]
[[0.14317562 0.16124352 0.21567544 ... 0.25585449 0.25657988 0.36646377]
 [0.22277101 0.20129765 0.13719067 ... 

KeyboardInterrupt: 

In [ ]:
D = pairwise_distances_chunked(X, metric=vicenty_distance)
for chunk in D:
    print(chunk)

[[    0.          2415.06222691 13171.45638864 ... 21791.58932116
  16802.1086868  40466.55615396]
 [ 2415.06222691     0.         11276.96605752 ... 20021.27059974
  14627.59489873 38658.11899464]
 [13171.45638864 11276.96605752     0.         ...  8783.72487311
   4617.99940445 27382.3231565 ]
 ...
 [ 2212.22679003  2149.94354715 13359.94993002 ... 22125.42124756
  16527.05593653 40739.17731026]
 [20130.77408826 19878.84948476 14420.40757314 ... 14398.55925556
  17765.67068848 28260.60100385]
 [14124.04662735 11712.70706966  7589.85338079 ... 13699.44550192
   6229.907762   30492.07525039]]
